targets:
  - name: baidu-home
    type: http
    url: https://www.baidu.com
    timeout: 3s

  - name: local-mysql
    type: tcp
    url: 127.0.0.1:3306
    timeout: 2s

  - name: k8s-api
    type: tcp
    url: 127.0.0.1:6443
    timeout: 1s
    
  - name: github-home
    type: http
    url: https://www.github.com
    timeout: 3s

  - name: dns-fail-test
    type: http
    url: http://xxx-not-exist-12345.com
    
  - name: non2xx-test
    type: http
    url: https://httpbin.org/status/500

  - name: bing
    type: http
    url: https://www.bing.com
    timeout: 3s

  - name: badssl-example
    type: cert
    url: badssl.com:443
    cert_warn_days: 14
